// <auto-generated />
using System;
using BrandMicroservice.src.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BrandMicroservice.src.Data.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20251026170058_CreateMakeTable")]
    partial class CreateMakeTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BrandMicroservice.src.Models.DbModels.Make", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("_id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("company");

                    b.Property<DateTime?>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMPTZ")
                        .HasColumnName("date_created")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("MakeAbbreviation")
                        .IsRequired()
                        .HasColumnType("VARCHAR(10)")
                        .HasColumnName("make_abbreviation");

                    b.Property<string>("MakeCode")
                        .IsRequired()
                        .HasColumnType("VARCHAR(20)")
                        .HasColumnName("make_code");

                    b.Property<string>("MakeLogo")
                        .HasColumnType("TEXT")
                        .HasColumnName("make_logo");

                    b.Property<string>("MakeName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("make_name");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("origin");

                    b.Property<int>("YearFounded")
                        .HasColumnType("integer")
                        .HasColumnName("year_founded");

                    b.HasKey("Id");

                    b.ToTable("makes", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
